export const productData = [
    {
        name: "Vest",
        category: "jackets",
        description:
            "A versatile and stylish vest that can be dressed up or down.",
        price: 70,
        isFeatured: true,
        isNew: false,
        onSale: false,
        brand: "fleurie",
        id: "Vest",
        img: "vest",
        isLimitedEdition: false,
    },
    {
        name: "Dressing Gown",
        category: "jackets",
        description:
            "Relax in style with this comfortable and luxurious dressing gown.",
        price: 120,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "fleurie",
        id: "DressingGown",
        img: "dressing-gown",
        isLimitedEdition: false,
    },
    {
        name: "Jeans",
        category: "pants",
        description:
            "A classic pair of denim jeans that never goes out of style.",
        price: 60,
        isFeatured: false,
        isNew: true,
        onSale: true,
        brand: "fleurie",
        id: "Jeans",
        img: "jeans",
        isLimitedEdition: true,
    },
    {
        name: "Backpack",
        category: "accessories",
        description:
            "A durable and practical backpack that's perfect for everyday use.",
        price: 80,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "fleurie",
        id: "Backpack",
        img: "backpack",
        isLimitedEdition: false,
    },
    {
        name: "Denim Shorts",
        category: "pants",
        description:
            "Stay cool and stylish on hot summer days with these denim shorts.",
        price: 40,
        isFeatured: true,
        isNew: false,
        onSale: true,
        brand: "fleurie",
        id: "DenimShorts",
        img: "denim-shorts",
        isLimitedEdition: false,
    },
    {
        name: "Purse",
        category: "accessories",
        description:
            "This stylish and functional purse is perfect for keeping your essentials organized.",
        price: 50,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "lumina",
        id: "Purse",
        img: "purse",
        isLimitedEdition: false,
    },
    {
        name: "Business Shirt",
        category: "shirts",
        description:
            "Look sharp and professional with this classic business shirt.",
        price: 65,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "lumina",
        id: "BusinessShirt",
        img: "business-shirt",
        isLimitedEdition: false,
    },
    {
        name: "Casual Boots",
        category: "shoes",
        description:
            "These comfortable and stylish casual boots are perfect for everyday wear.",
        price: 120,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "lumina",
        id: "CasualBoots",
        img: "casual-boots",
        isLimitedEdition: true,
    },
    {
        name: "Bra",
        category: "underwear",
        description:
            "A comfortable and supportive bra that's perfect for everyday wear.",
        price: 30,
        isFeatured: false,
        isNew: false,
        onSale: true,
        brand: "lumina",
        id: "Bra",
        img: "bra",
        isLimitedEdition: false,
    },
    {
        name: "Underwear",
        category: "underwear",
        description:
            "Stay comfortable all day with these soft and breathable underwear.",
        price: 20,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "lumina",
        id: "Underwear",
        img: "underwear",
        isLimitedEdition: false,
    },
    {
        name: "Formal Shoes",
        category: "shoes",
        description:
            "Look sharp and sophisticated with these elegant formal shoes.",
        price: 150,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "altitude",
        id: "FormalShoes",
        img: "formal-shoes",
        isLimitedEdition: false,
    },
    {
        name: "Summer Dress",
        category: "dresses",
        description:
            "Stay cool and stylish on hot summer days with this beautiful summer dress.",
        price: 90,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "altitude",
        id: "SummerDress",
        img: "summer-dress",
        isLimitedEdition: true,
    },
    {
        name: "Runners",
        category: "shoes",
        description:
            "These comfortable and durable runners are perfect for a morning jog or a long-distance run.",
        price: 80,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "altitude",
        id: "Runners",
        img: "runners",
        isLimitedEdition: false,
    },
    {
        name: "Winter Jacket",
        category: "jackets",
        description:
            "Stay warm and stylish in the coldest of weather with this insulated winter jacket.",
        price: 250,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "altitude",
        id: "WinterJacket",
        img: "winter-jacket",
        isLimitedEdition: false,
    },
    {
        name: "Beanie",
        category: "accessories",
        description:
            "Stay warm and stylish with this cozy and comfortable beanie.",
        price: 20,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "altitude",
        id: "Beanie",
        img: "beanie",
        isLimitedEdition: false,
    },
    {
        name: "Flats",
        category: "shoes",
        description:
            "Stay comfortable and stylish with these versatile and elegant flats.",
        price: 100,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "novo",
        id: "Flats",
        img: "flats",
        isLimitedEdition: false,
    },
    {
        name: "Bowtie",
        category: "accessories",
        description:
            "Make a statement with this stylish and sophisticated bowtie.",
        price: 30,
        isFeatured: false,
        isNew: false,
        onSale: true,
        brand: "novo",
        id: "Bowtie",
        img: "bowtie",
        isLimitedEdition: false,
    },
    {
        name: "Sunglasses",
        category: "accessories",
        description:
            "Protect your eyes and look cool with these stylish and high-quality sunglasses.",
        price: 50,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "novo",
        id: "Sunglasses",
        img: "sunglasses",
        isLimitedEdition: true,
    },
    {
        name: "High Heels",
        category: "shoes",
        description:
            "Look and feel confident with these elegant and stylish high heels.",
        price: 120,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "novo",
        id: "HighHeels",
        img: "high-heels",
        isLimitedEdition: false,
    },
    {
        name: "Formal Jacket",
        category: "jackets",
        description:
            "Make a statement with this stylish and sophisticated formal jacket.",
        price: 200,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "novo",
        id: "FormalJacket",
        img: "formal-jacket",
        isLimitedEdition: false,
    },
    {
        name: "Watch",
        category: "accessories",
        description:
            "Stay on time and on trend with this stylish and functional watch.",
        price: 150,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "novo",
        id: "Watch",
        img: "watch",
        isLimitedEdition: false,
    },
    {
        name: "Jumper",
        category: "jackets",
        description:
            "Stay warm and cozy in the cooler months with this soft and comfortable jumper.",
        price: 80,
        isFeatured: false,
        isNew: false,
        onSale: true,
        brand: "altitude",
        id: "Jumper",
        img: "jumper",
        isLimitedEdition: false,
    },
    {
        name: "Cap",
        category: "accessories",
        description:
            "Stay cool and stylish on hot summer days with this trendy and comfortable cap.",
        price: 25,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "altitude",
        id: "Cap",
        img: "cap",
        isLimitedEdition: false,
    },
    {
        name: "Formal Dress",
        category: "dresses",
        description:
            "Look and feel elegant and sophisticated with this stunning formal dress.",
        price: 300,
        isFeatured: true,
        isNew: true,
        onSale: false,
        brand: "altitude",
        id: "FormalDress",
        img: "formal-dress",
        isLimitedEdition: false,
    },
    {
        name: "Hoodie",
        category: "jackets",
        description:
            "Stay comfortable and cozy in this soft and stylish hoodie.",
        price: 60,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "altitude",
        id: "Hoodie",
        img: "hoodie",
        isLimitedEdition: false,
    },
    {
        name: "Necklace",
        category: "accessories",
        description:
            "Add some sparkle to your outfit with this elegant and eye-catching necklace.",
        price: 40,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "altitude",
        id: "Necklace",
        img: "necklace",
        isLimitedEdition: false,
    },
    {
        name: "Scarf",
        category: "accessories",
        description:
            "Stay warm and stylish in the cooler months with this cozy and comfortable scarf.",
        price: 30,
        isFeatured: false,
        isNew: false,
        onSale: true,
        brand: "lumina",
        id: "Scarf",
        img: "scarf",
        isLimitedEdition: false,
    },
    {
        name: "Polo Shirt",
        category: "shirts",
        description:
            "Stay cool and stylish on warm days with this comfortable and versatile short-sleeve shirt.",
        price: 35,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "lumina",
        id: "PoloShirt",
        img: "polo-shirt",
        isLimitedEdition: false,
    },
    {
        name: "Skirt",
        category: "skirts",
        description:
            "Look and feel elegant and feminine with this versatile and stylish skirt.",
        price: 80,
        isFeatured: true,
        isNew: true,
        onSale: false,
        brand: "lumina",
        id: "Skirt",
        img: "skirt",
        isLimitedEdition: false,
    },
    {
        name: "Swimsuit",
        category: "swimwear",
        description:
            "Hit the beach or the pool in style with this comfortable and fashionable swimsuit.",
        price: 50,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "lumina",
        id: "Swimsuit",
        img: "swimsuit",
        isLimitedEdition: false,
    },
    {
        name: "Singlet",
        category: "shirts",
        description:
            "Stay cool and comfortable on hot summer days with this stylish and practical singlet.",
        price: 25,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "lumina",
        id: "Singlet",
        img: "singlet",
        isLimitedEdition: false,
    },
    {
        name: "Trenchcoat",
        category: "jackets",
        description:
            "Stay stylish and dry in the rain with this classic and sophisticated trenchcoat.",
        price: 150,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "lumina",
        id: "Trenchcoat",
        img: "trenchcoat",
        isLimitedEdition: false,
    },
    {
        name: "Socks",
        category: "accessories",
        description:
            "Stay comfortable and stylish from head to toe with these soft and cozy socks.",
        price: 10,
        isFeatured: false,
        isNew: false,
        onSale: true,
        brand: "fleurie",
        id: "Socks",
        img: "socks",
        isLimitedEdition: false,
    },
    {
        name: "Mittens",
        category: "accessories",
        description:
            "Stay warm and cozy in the cooler months with these soft and comfortable mittens.",
        price: 20,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "fleurie",
        id: "Mittens",
        img: "mittens",
        isLimitedEdition: false,
    },
    {
        name: "Ugg Boots",
        category: "shoes",
        description:
            "Stay warm and comfortable in the cooler months with these soft and cozy Ugg boots.",
        price: 120,
        isFeatured: false,
        isNew: false,
        onSale: false,
        brand: "fleurie",
        id: "UggBoots",
        img: "ugg-boots",
        isLimitedEdition: false,
    },
    {
        name: "Long Boots",
        category: "shoes",
        description:
            "Stay stylish and comfortable in the cooler months with these elegant and versatile long boots.",
        price: 150,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "fleurie",
        id: "LongBoots",
        img: "long-boots",
        isLimitedEdition: false,
    },
    {
        name: "Belt",
        category: "accessories",
        description:
            "Complete your outfit with this stylish and functional belt.",
        price: 30,
        isFeatured: false,
        isNew: true,
        onSale: false,
        brand: "fleurie",
        id: "Belt",
        img: "belt",
        isLimitedEdition: false,
    },
    {
        name: "Slippers",
        category: "shoes",
        description:
            "Stay relaxed at home with these soft and comfortable slippers.",
        price: 50,
        isFeatured: false,
        isNew: true,
        onSale: true,
        brand: "lumina",
        id: "Slippers",
        img: "slippers",
        isLimitedEdition: false,
    },
]

export default productData
